server:
  session-timeout: 1800
  tomcat:
  #    max-threads: 1000
  #    min-spare-threads: 30
     max-file-size: -1
     max-request-size: -1
  port: 9089
  uri-encoding: utf-8
system:
  #注册用户默认密码
  defaultPwd: 123456
  #注册用户默认角色ID
  defaultRoleId: 100
  #注册用户默认组织机构ID
  defaultOrgId: 0
  #不需要数据权限过滤的角色key
  noDataFilterRole: DATA_NO_FILTER
  #用户每日收取短信上限
  smsTimes: 25
  #不同终端用户的超时时间（web用户3小时，app，微信，小程序时间自己定半年或永久）Long型，后面记得加l
  expireTime: "{web: 10800000l, app: 15768000000l}"
controller:
  #扫描controller中不需要鉴权的method
  scanPackage: classpath*:com/jeebase/*/*/controller/
     #打包时扫描的时class文件
#日志
logging:
  path: /Users/fanyouyi/Downloads/loggs
  config: classpath:config/logback-spring.xml
# 动态多数据源配置
spring:
  datasource:
    druid:
      # 用于采集web-jdbc关联监控的数据
      webStatFilter:
        enabled: true
      # 用于展示Druid的统计信息（提供监控信息展示的html页面+提供监控信息的JSON Api）
      statViewServlet:
        enabled: true
        # 设置ip白名单（逗号隔开），不填则允许所有访问
        allow:
        # ip黑名单（优先于allow）
        deny:
        # 监控页面的url
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        # 用于统计监控信息
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          # 慢sql标准，单位毫秒
          slow-sql-millis: 1000
          # 合并sql
          merge-sql: true
        wall:
          config:
            # 是否允许一次执行多条语句，默认关闭
            multi-statement-allow: true
    dynamic:
      primary: master   #设置默认的数据源
      druid: #以下是支持的全局默认值，每个库还可重新设置独立参数
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
      datasource:
        #主库数据源
        master:
          url: jdbc:oracle:thin:@192.168.0.103:1521:xe
          username: zjweb
          password: Zjkj0413
          driver-class-name: oracle.jdbc.driver.OracleDriver
        #从库数据源
#        slave:
#          url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/com/jeebase/*/*/mapper/*Mapper.xml
  typeAliasesPackage: com.jeebase.*.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null' #注意：单引号
j2cache:
  config-location: classpath:config/j2cache.properties
  open-spring-cache: true
  j2CacheConfig:
    serialization: fastjson
  cache-clean-mode: active
  redis-client: jedis
qiniu:
  access-key:
  secret-key:
  zone: zone0
  bucket: mall
  base-url: http://img.jeebase.com/
aliyun:
  AccessKey-ID:
  Access-Key-Secret:
  sign-name:
  reg-code:
baidu:
  ai.clientId:
  ai.clientSecret:
  ai.token: 24.f764775339f1f2357f06d019d134aedb.2592000.1632493647.282335-24753599
restTemplate:
  #连接池的最大连接数默认为0
  maxTotalConnect: 0
  #单个主机的最大连接数
  maxConnectPerRoute: 200
  #连接超时默认2s
  connectTimeout: 2000
  #读取超时默认30s
  readTimeout: 30000
xxlJob:
  #xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
  admin.addresses: http://127.0.0.1:8080/xxl-job-admin
  #xxl-job 执行器AppName[选填]，为空则关闭自动注册
  executor.appname: hisc-v3
  executor.address:
  #xxl-job 执行器IP[选填]，为空则自动获取
  executor.ip:
  #xxl-job 执行器端口号[必须]
  executor.port: 9999
  # xxl-job 访问令牌，非空则进行匹配校验[选填]
  accessToken: HiscJobTokenTest
  # xxl-job 执行器日志路径
  executor.logpath: /Users/fanyouyi/Downloads/jobhandler
  # xxl-job log retention days
  executor.logretentiondays: -1
hostp:
   id: 2
   hospitalName: 抚顺市眼病医院
   dept:
         code: off
         #off
   payType: NYBANK

weixin:
  backUrl: http://zjkj.ngrok2.xiaomiqiu.cn/wechat/auth/login
  # 域名
  domain: http://231o6o7661.51mypc.cn/
  #http://231o6o7661.51mypc.cn/
  api.appId: wxb3acb24d196ae55c
  api.mchid: 1521988381
  api.key: C5FDE9DE2D29789A81D1BC0F16292048
  #眼病 ea5b1404904089f7de129d3cc7b12fe1
  api.secret: ea5b1404904089f7de129d3cc7b12fe1
  #获取access_token的URL,有效期目前为2个小时
  api.accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={appId}&secret={appSecret}
  #获取openId
  api.accessWebTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid={appId}&secret={appSecret}&code={code}&grant_type=authorization_code
  #获取帐号下所有模板信息
  api.queryTemplateListUrl: https://api.weixin.qq.com/cgi-bin/template/get_all_private_template?access_token={accessToken}
  #发送微信模板信息
  api.sendTemplateMsgUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token={accessToken}
  #获取用户增减数据(最大时间跨度7天)
  api.queryUserSummaryUrl: https://api.weixin.qq.com/datacube/getusersummary?access_token={accessToken}
  #获取用户总关注数(最大时间跨度7天)
  api.queryUserCumulateUrl: https://api.weixin.qq.com/datacube/getusercumulate?access_token={accessToken}
  #获取jsapi_ticket
  api.queryJsApiTicketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token={accessToken}&type=jsapi
  #获取用户关注列表
  api.queryAttentionUserList: https://api.weixin.qq.com/cgi-bin/user/get?access_token={accessToken}&next_openid={nextOpenId}
  #批量获取用户信息
  api.queryUserInfoList: https://api.weixin.qq.com/cgi-bin/user/info/batchget?access_token={accessToken}
  #小程序ID
  app.appId:
  #小程序密钥
  app.secret:
  #商户号
  app.mchId: 1521988381
  #支付签名
  app.paySignKey: C5FDE9DE2D29789A81D1BC0F16292048
  #交易类型
  app.tradeType: JSAPI
  #证书名称，对应不同的商户号
  app.certName: /cert/apiclient_cert.p12
  #获取code的请求地址
  app.getCode: https://open.weixin.qq.com/connect/oauth2/authorize?appid={appId}&redirect_uri={rediretUri}&response_type=code&scope={scope}&state=STAT#wechat_redirect
  #小程序登录
  app.queryUserInfoUrl: https://api.weixin.qq.com/sns/jscode2session?appid={appId}&secret={appSecret}&js_code={code}&grant_type=authorization_code
  #拉取用户信息的请求地址
  app.userMessage: https://api.weixin.qq.com/sns/userinfo?access_token={accessToken}&openid={openId}&lang=zh_CN
  #支付回调地址
  app.notifyUrl: https://jeebase.com/wechat/api/notify
  #微信统一下单接口路径
  app.uniformorder: https://api.mch.weixin.qq.com/pay/unifiedorder
  #退款地址
  app.refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  #退款查询地址
  app.refundqueryUrl: https://api.mch.weixin.qq.com/pay/refundquery
  #微信查询订单状态
  app.orderquery: https://api.mch.weixin.qq.com/pay/orderquery
  # minio文件存储配置信息
minio:
  bucketName: zjkj-img
  endpoint: http://61.240.137.161:9000/
  accesskey: zjkj-minio
  secretKey: Zjkj@0413.
alipay:
  appid: 2021003146632241
  # 仅支持JSON
  format: JSON
  # 请求使用的编码格式
  charset: utf-8
  # 商户生成签名字符串所使用的签名算法类型，目前支持RSA2和RSA，推荐使用RSA2
  signType: RSA2
  # 支付宝网关 https://openapi.alipaydev.com/gateway.do  https://openapi.alipay.com/gateway.do
  serverUrl: https://openapi.alipay.com/gateway.do
  # 商户私钥
  myPrivateKey: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCzxa9yjmLzM5Gmx8kYhGKeH1+tjPOdfRvqF4JqTVRuy6u4oHQa10LUWt28hOFMbZRoKRPtjBgXsp9MO7JUNIigO81bxqpTa1OR/8+K1thpyLnmOU7gMT0qW5eT+e1upBmPs2pl1DwsCPW0Rt0fuuPtzN9pF7E2DcnzXxSE8g2kDLakhW3n8gWUVEd+09QDGmk9L4eBp1D1yVjPxv+x3Kq90WGKdX5qP2IZwQ5wv6WZKCITvl3hhY51LGNSbcA5Bbo0sL2xzJlmEXwZboiNbwy/dPm3x7bTXk3RaZheCqscboZG4ffr7UIzW1QwoJ1UEinsY0Gh2xWYMr+mcpxNnCvTAgMBAAECggEBAJlRbrlfkCpkf8LivrHnLgg3L61e+eIF8kmqdTJd8zVvBGw4g+zkS326ZUPDfDZnelt/NRyyD1Yeo9crToKcLy2g8xpji54LecGZjxKU+wr1Av7DP27a75Rxewvb6lAjKh2xYXupDwxrM8nlae8GwB9uS9dgOmWkSukB3QkpOtL+Cr+wzFn3GnkjJzs0Ep5yCSSpnVh3nq2ejfriOWJKjVH37GzsTkODWlPMH8Q17XhDQ6Z3B1QTwd8q2ODGQYLiiGkh3+dh30StJROs8cTQ2y1cmGuUnVq+A9xII9p4f3OmbxpNtiWBSJfFVb+KC5RtzE6D+VVYdAcIqHAk+GLExOECgYEA21N7BgRzEKBqxr6oGkD4WBZgfQSGGM8uJxanpZlRlQki62oRaQkpAAFLcCeFnPfGhaxvM+mhyXCl3JEQPeYn063HjnjZaEd8t3dKLvatV0UOSzGMrpg5H6SAUR8l6RUD2HO5Wibzd4q+emgwP9YGcQpcJ0jX+KZYykTgZOTt+8MCgYEA0dUNe8bhpzP/7QGUNs3VGoF19gUDw3cNK1TvRvLHrq5xMfSxU9AAuWgl3sYAWQoGoEZpSSB157HPCPZhV2SdYyaQw5BsW4iztoJIO89F8qi/vWCGwa5OviSTR7zPbtam7YXJWd8x/8itylksbnIub8SgVDZU/u23iUtcKKJq3rECgYEAgOJduPuEYpDiLkh7oHHtflYn/U9bPdkB1haKDdY7CsmDq7N457BqV4ZrPkz7R3KTRpo9/tOcLzPzQ9o7ISTO4qWMTzzVBWJ895MyFMcAtffunmFPuonZh66zePhE3uNqjxfyI/gfum/d3zC6qciroGHmJW+4+nVGWBaBhsjA0OECgYBNWPnVbKR1nAd0+CYIZatuT9aJz6NphBMIrBBf2NKeo5L6VTagrIX30lpTWi16pOV4YzwgRqTvuW2V4ixTqLUTfX3TeQNYYnXMiw3RbkBciLPVPSWvc293S8g2o3TbaKiz2aM1S78EiJb3hhOIyvIvJQ3svPJr3njPVUYtfGFkoQKBgQCR40ZIlWP6++SUwg5Xdrwlrd75sDGDwHqUlQuIwFNUwXleCUg13eMtNQfnHfuNzI6DxDjx8uymDr59/iB0RJq0lRcLVjsu60Dnnh+8cX3ktoSzr8MGSooeaZxDfM7qc8dVxpm9YR1QDgwlnMyXBVFeTYe5OytIfwEl3djCMNzJcg=="
  # 支付宝公钥
  alipayPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA/ctrIdwRcGnNATDrnGyRJncb3w2jLDO/j1d3YYn158JrizHuTXERA5BcLEr4hWu27/R7EmCt2DknG2oAaaRd7UQQE4NviU6cHn+9hJIUb79QJCBJfuL+jELVDvvyaV/qFtGcVhNLoWLQVIGIMqinDLtBkUqzKTMkT+If2brLfzeuzJPcPP86zdhKW7X8Zrb2gARt/qzpFq0cRtRi6/t+OogetULzN+UjNAWYsW+826c13I1XQfRm+2Z8pfzrUQVbb34oegJ/e5S5y54p4MlLner77rcdTcmslZsk3gs2faQeftvvkpTzHMQwp8y8X0Ih91kvQxb3HqAuo1R4XhbQkwIDAQAB"
  #服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notifyUrl: http://fscrsapp.natapp1.cc/notify/aliQR
  #页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  returnUrl:
  #保存支付日志的地址
  logPath: D:/zjkj/AL/log

